// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using squittal.ScrimPlanetmans.Data;

namespace squittal.ScrimPlanetmans.App.Migrations
{
    [DbContext(typeof(PlanetmansDbContext))]
    [Migration("20200216192554_AddActionPointsItemCategoryModels")]
    partial class AddActionPointsItemCategoryModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("squittal.ScrimPlanetmans.ScrimMatch.Models.ItemCategoryRule", b =>
                {
                    b.Property<int>("RulesetId")
                        .HasColumnType("int");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("ScrimRulesetId")
                        .HasColumnType("int");

                    b.HasKey("RulesetId", "ItemCategoryId");

                    b.HasIndex("ScrimRulesetId");

                    b.ToTable("ItemCategoryRule");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.ScrimMatch.Models.ScrimActionModel", b =>
                {
                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Action");

                    b.ToTable("ScrimAction");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.ScrimMatch.Models.ScrimActionPoints", b =>
                {
                    b.Property<int>("RulesetId")
                        .HasColumnType("int");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int?>("ActionModelAction")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("ScrimRulesetId")
                        .HasColumnType("int");

                    b.HasKey("RulesetId", "Action");

                    b.HasIndex("ActionModelAction");

                    b.HasIndex("ScrimRulesetId");

                    b.ToTable("ScrimActionPoints");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.ScrimMatch.Models.ScrimRuleset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScrimRuleset");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.Shared.Models.Planetside.Faction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodeTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserSelectable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Faction");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.Shared.Models.Planetside.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FactionId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVehicleWeapon")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxStackSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.Shared.Models.Planetside.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemCategory");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.Shared.Models.Planetside.Loadout", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loadout");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.Shared.Models.Planetside.Profile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.Shared.Models.Planetside.World", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("World");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.Shared.Models.Planetside.Zone", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HexSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.ScrimMatch.Models.ItemCategoryRule", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.ScrimMatch.Models.ScrimRuleset", null)
                        .WithMany("ItemCategoryRules")
                        .HasForeignKey("ScrimRulesetId");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.ScrimMatch.Models.ScrimActionPoints", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.ScrimMatch.Models.ScrimActionModel", "ActionModel")
                        .WithMany()
                        .HasForeignKey("ActionModelAction");

                    b.HasOne("squittal.ScrimPlanetmans.ScrimMatch.Models.ScrimRuleset", null)
                        .WithMany("ActionRules")
                        .HasForeignKey("ScrimRulesetId");
                });
#pragma warning restore 612, 618
        }
    }
}
